# Site settings
title: Mylium
email: info@mylium.eu
description: >  # this means to ignore newlines until "baseurl:"
  FPGA engineering for new space, defence and dual-use projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.mylium.eu" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown

# Include tools directory
include:
  - tools

# Exclude node_modules and other unnecessary files
exclude:
  - node_modules
  - vendor
  - .git
